version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
